language: python

python:
  - "2.7"

branches:
  only: source

notifications:
  email:
    on_success: always
    on_failure: always


before_install:
  - remotesha=`git rev-parse origin/source`
  - echo $remotesha
  - localsha=`git rev-parse HEAD`
  - echo $localsha
  - range="${remotesha}..${localsha}"
  - echo $range
  - sourcecommitmessages=`git log --pretty=format:%B $range`
  - echo $sourcecommitmessages
  - deploy=`git rev-list -n 1 --grep '[deploy]' "$range"`
  - commitmessage=`printf "Deploy compiled site from source commit $localsha \n$sourcecommitmessages"`
  - echo $commitmessage
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "travis"


install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libxslt1-dev yui-compressor
  - pip install -r requirements.txt


script:
  - nikola build


after_success:
  - if [[ "$TRAVIS_BRANCH" == "source" ]] && [ -n "$deploy" ]; then
    sudo apt-get install git &&
    sudo chmod +x /usr/share/doc/git/contrib/subtree/git-subtree.sh &&
    sudo ln -s /usr/share/doc/git/contrib/subtree/git-subtree.sh /usr/lib/git-core/git-subtree &&    
    echo "Deploying to master" &&
    nikola clean &&
    rm -rf _site &&
    nikola build &&
    nikola deploy &&
    git stash &&
    git checkout -b temp1 &&
    git add -f _site/ &&
    git commit --allow-empty-message -m '' &&
    git subtree --prefix=_site/ split -b temp2 &&
    git checkout master &&
    git merge --squash -X theirs temp2 &&
    git commit -m "$commitmessage" &&
    git branch -D temp1 &&
    git branch -D temp2 &&
    git checkout source &&
    git stash pop;
    fi
