name: Simon van der Veldt
encoding: UTF-8
markdown: kramdown
pygments: false
permalink: /:title
category_title_prefix: 'Posts in category '
exclude: README.md

kramdown:
    input: GFM
    enable_coderay: true
    use_coderay: true
    coderay:
        coderay_line_numbers: table
        coderay_bold_every: false
        coderay_css: class