# Site settings
title: "Simon van der Veldt"
description: ""
baseurl: ""
url: "http://simonvanderveldt.nl"
author: Simon van der Veldt
permalink: /:title
include: ["_pages", ".well-known"]
exclude: ["vendor"]

# Build settings
theme: null
kramdown:
  hard_wrap: true
sass:
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  links:
    - https://github.com/simonvanderveldt
    - https://keybase.io/simonvanderveldt
    - https://www.linkedin.com/in/simonvanderveldt

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
