# Site settings
name: "Simon van der Veldt"
baseurl: ""
url: "http://simonvanderveldt.nl"
author: Simon van der Veldt
permalink: /:title
include: ["_pages"]
exclude: ["vendor"]

# Build settings
kramdown:
  hard_wrap: true
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
